### ISSUE TITLE
Error message when using struc_preproc.sh

### ISSUE THREAD

**Issue by edwardsaunders7** [SPMIC-UoN/BRC_Pipeline#1]
I am attempting to use the BRC Pipeline on the UoN HPC cluster -  I have followed the setup process and edited all the necessary path locations for FSL, Cuda, etc.

I am trying to test my setup using an example file from the UKBiobank:

1) `bash BRC_structural_pipeline/struc_preproc.sh --input gpfs01/share/HearingMRI/HighResConn/Edward/Scripts/1040891/T1/T1.nii.gz --path Example_Run/ --subject Example` 

Upon running this script, I am receiving error message "BRC_structural_pipeline/struc_preproc.sh: line 286: /Show_version.sh: No such file or directory"

- To remedy this, I checked that these files existed in their proper locations, and that the global directory was set correctly in my SetUpBRCPipeline.sh, which all seems okay.

2. Ran `bash Show_version.sh`, to which I am presented with the following error:
" Show_version.sh: line 42: /log.shlib: No such file or directory"

3. Checked existence of log.shlib:
`scripts]$ ls`
`log.shlib`
File seems to exist in the correct location

Any suggestions? 

Thanks :)

**Comment by stefanpsz** [comment]
Hi

Can you please check that you have correctly set up the BRCDIR environmental variable in SetUpBRCPipeline.sh?

If you think it is correctly configure, can you please post the contents of that file here?

Thanks!

Stefan

**Comment by Alirezamnk** [comment]
Hi,
To run the BRC Pipeline within the UoN HPC cluster, you just need to load its module:
module load brc-pipelines-img

Please remove all the initialisation that you added to your bash_profile, as well.
Then, run the pipeline using the following command:

struc_preproc.sh --input gpfs01/share/HearingMRI/HighResConn/Edward/Scripts/1040891/T1/T1.nii.gz --path Example_Run/ --subject Example

BW,
Ali

**Comment by edwardsaunders7** [comment]
@Alirezamnk , Thanks! This solved the issue :)
Problem was that I had not loaded the brc-pipeline-img module. I had to specify that it was the brc-pipeline-img/1.0 module in order for it to work
 Have got an example job now running on the SLURM queue 

Thanks!
